services:
  moodleapp:
    build:
      context: .
    image: moodleapp:1.0
    container_name: moodleapp
    ports:
      - 80:80
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - moodledb
  # MySQL DB Service
  moodledb:
    image: mysql:8.0.36
    container_name: clouddb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - clouddbdata:/var/lib/mysql
    # environment:
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}

  # phpmyadmin to Manage MySQL DB
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: clouddb
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - moodledb

volumes:
  clouddbdata:
  moodledata: