version: '3.8'

services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodleapp
    ports:
      - "80:80"
    volumes:
      # Bind mount for moodledata directory
      - ./moodledata:/var/www/moodledata
      # (Optional) Mount the moodle source code (for local development)
      - ./moodle:/var/www/html
    depends_on:
      - db
    environment:
      MOODLE_URL: http://localhost
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodledb
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: moodlepass

  db:
    image: mysql:8.0
    container_name: moodledb
    restart: always
    environment:
      MYSQL_DATABASE: moodledb
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      # Bind mount MySQL data to a host folder
      - ./mysql-data:/var/lib/mysql

