services:
  moodleapp:
    build:
      context: .
      dockerfile: Moodle
    image: moodle-web:1.0
    container_name: moodle-web
    ports:
      - 80:80
    volumes:
      - moodledata:/var/www/moodledata
      - moodlefile:/var/www/html
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${moodledb}
      - POSTGRES_USER=${dbuser}
      - POSTGRES_PASSWORD=${dbpassword}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadminemail}
      - PGADMIN_DEFAULT_PASSWORD=${pgadminpassword}
    depends_on:
      - postgres

volumes:
  pgdata:
  moodledata:
  moodlefile: